name: env_tutorial
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: [pull_request, push] 

env:
  ## Sets environment variable
  AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  AWS_BUCKET_REGION: ${{secrets.AWS_BUCKET_REGION}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}} 

jobs:
  trying-to-use-environment-secrets:
    runs-on: ubuntu-latest
    environment: test-env #<---The only difference we need to specify what environment to use for environment secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          echo ${{ secrets.AWS_BUCKET_NAME }}
          echo "DEV_SERVER_URL=${{ secrets.AWS_BUCKET_NAME_REPOSITORY }}"